controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\MainDashboardController::index

api_auth_login:
    path: /api/auth/login
    controller: Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandler::handle
    methods: [POST]